apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
  - ../../bases

patches:
  - path: deployment.patch.yaml
  - target:
      version: v1
      kind: Service
      name: app1
    path: service.patch.yaml